import pandas as pd

import matplotlib.pyplot as plt

data1 = pd.read_csv("osr4.csv")
data2 = pd.read_csv("osr2.csv")
data3 = pd.read_csv("noFilter.csv")
# print(data.head())
# print(data.columns)

times1 = len(data1)
times2 = len(data2)
times3 = len(data3)
fig, (ax1,ax2,ax3) = plt.subplots(nrows=3, ncols=1, sharey=True, sharex=True)
ax1.plot(range(times1), 100*data1["pitch_raw"][:times1], label="pitch_raw")
ax1.plot(range(times1), 100*data1["pitch_filter"][:times1], label="pitch_filter")
ax1.plot(range(times1), data1["motor_front"][:times1], label="motor_front")
ax1.plot(range(times1), data1["motor_back"][:times1], label="motor_back")
ax2.plot(range(times2), 100*data2["pitch_raw"][:times2], label="pitch_raw")
ax2.plot(range(times2), 100*data2["pitch_filter"][:times2], label="pitch_filter")
ax2.plot(range(times2), data2["motor_front"][:times2], label="motor_front")
ax2.plot(range(times2), data2["motor_back"][:times2], label="motor_back")
ax3.plot(range(times3), 100*data3["pitch_raw"][:times3], label="pitch_raw")
ax3.plot(range(times3), 100*data3["pitch_filter"][:times3], label="pitch_filter")
ax3.plot(range(times3), data3["motor_front"][:times3], label="motor_front")
ax3.plot(range(times3), data3["motor_back"][:times3], label="motor_back")
plt.legend()
ax1.set_title("Week 4 Milestone 5 OSR4")
ax2.set_title("Week 4 Milestone 5 OSR2")
ax3.set_title("Week 4 Milestone 5 NoFilter")
plt.savefig("w4m5.png")
plt.show()
